// Class automatically generated by Dev-C++ New Class wizard

#ifndef GAMESTATE_H
#define GAMESTATE_H

#include <string>
#include <cstring>
using namespace std;

class GameState
{
    public:
        string location;
        string inventory;
        int health;
        int genOnce;
        int notice;
        int giveHint;
        bool demonPresent;
        bool videotapeOn;
        bool pathOpen;
        bool batteryIn;
        bool labOn;
        bool doorOpen;
        bool childOnce;
        bool pastTurnstile;
        bool descripOnce;
        bool iOnce;
        
		GameState(bool newGame);
		void save(string location, string inventory);
		void load();
		string getLocation();
		string getInventory();
		
};

#endif // GAMESTATE_H
